apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'api-gateway'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['api-gateway.medicab.svc.cluster.local:8080']

      - job_name: 'auth-service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['auth-service.medicab.svc.cluster.local:8080']

      - job_name: 'patient-service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['patient-service.medicab.svc.cluster.local:8080']

      - job_name: 'appointment-service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['appointment-service.medicab.svc.cluster.local:8080']

      - job_name: 'billing-service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['billing-service.medicab.svc.cluster.local:8080']

      - job_name: 'medical-record-service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['medical-record-service.medicab.svc.cluster.local:8080']

      - job_name: 'ordonnance-service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['ordonnance-service.medicab.svc.cluster.local:8080']

      - job_name: 'config-service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['config-service.medicab.svc.cluster.local:9999']

      - job_name: 'discovery-service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['discovery-service.medicab.svc.cluster.local:8761']

      - job_name: 'ai-service'
        metrics_path: '/metrics'
        static_configs:
          - targets: ['ai-service.medicab.svc.cluster.local:8000']
