spring.application.name=medical-record-service

spring.config.import=${CONFIG_URL:optional:configserver:http://localhost:9999?ssl=false}
spring.cloud.config.fail-fast=false

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.metrics.tags.application=${spring.application.name}