services:
  postgres:
    image: postgres:16-alpine
    container_name: medicab-postgres-local
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=medicab
      - POSTGRES_PASSWORD=medicab123
      - POSTGRES_MULTIPLE_DATABASES=authdb,patientdb,appointmentdb,billingdb,recorddb,ordonnancedb
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh

  redis:
    image: redis:7-alpine
    container_name: medicab-redis-local
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: medicab-rabbitmq-local
    ports:
      - "5672:5672"
      - "15672:15672"
