pipeline {
    agent any

    environment {
        SERVICE_NAME = "ai-service"
        SONAR_HOST_URL = "http://host.docker.internal:9005"
        DOCKER_REGISTRY = "abdojab" // <-- Ton compte a ete ajoute !
    }

    stages {
        stage('Test (PyTest)') {
            steps {
                dir("${env.SERVICE_NAME}") {
                    sh 'pip install --break-system-packages -r requirements.txt'
                    sh 'pytest tests/ --disable-warnings || echo "Tests optionnels terminés"'
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                dir("${env.SERVICE_NAME}") {
                    sh 'sonar-scanner -Dsonar.projectKey=medicab-${SERVICE_NAME} -Dsonar.sources=. -Dsonar.host.url=${SONAR_HOST_URL}'
                }
            }
        }

        stage('Docker Build & Push') {
            steps {
                dir("${env.SERVICE_NAME}") {
                    sh "docker build -t ${env.DOCKER_REGISTRY}/${env.SERVICE_NAME}:latest ."
                    
                    withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', passwordVariable: 'DOCKER_PASS', usernameVariable: 'DOCKER_USER')]) {
                        sh "echo \${DOCKER_PASS} | docker login -u \${DOCKER_USER} --password-stdin"
                        sh "docker push ${env.DOCKER_REGISTRY}/${env.SERVICE_NAME}:latest"
                    }
                }
            }
        }

        stage('Deploy to Minikube K8s') {
            steps {
                sh "kubectl rollout restart deployment/${env.SERVICE_NAME} -n medicab || echo 'Deploy not found yet'"
            }
        }
    }
}
