apiVersion: apps/v1
kind: Deployment
metadata:
  name: medical-record-service
  namespace: medicab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: medical-record-service
  template:
    metadata:
      labels:
        app: medical-record-service
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: medical-record-service
          image: abdojab/medical-record-service:11
          imagePullPolicy: IfNotPresent
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://discovery-service:8761/eureka"

            # ✅ CORRIGÉ — MySQL
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql:3306/medical_record_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC"
            - name: SPRING_DATASOURCE_USERNAME
              value: "root"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "Medicab2026!"
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              value: "com.mysql.cj.jdbc.Driver"

            # ✅ CORRIGÉ — Dialect MySQL
            - name: SPRING_JPA_DATABASE_PLATFORM
              value: "org.hibernate.dialect.MySQLDialect"
            - name: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
              value: "org.hibernate.dialect.MySQLDialect"

            - name: SPRING_CLOUD_CONFIG_URI
              value: "http://config-service:9999"
            - name: SPRING_CONFIG_IMPORT
              value: "optional:configserver:http://config-service:9999"
          ports:
            - containerPort: 8084
---
apiVersion: v1
kind: Service
metadata:
  name: medical-record-service
  namespace: medicab
spec:
  ports:
    - port: 8080
      targetPort: 8084
  selector:
    app: medical-record-service