pipeline {
    agent any

    tools {
        maven 'Maven 3'
    }

    environment {
        SERVICE_NAME = "billing-service"
        DOCKER_REGISTRY = "abdojab"
        SONAR_TOKEN = credentials('tockensonarqube')
    }

    stages {
        stage('Build & Test') {
            steps {
                dir("${env.SERVICE_NAME}") {
                    sh 'mvn clean package -DskipTests=true -B'
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                dir("${env.SERVICE_NAME}") {
                    sh """
                        mvn sonar:sonar \
                          -Dsonar.projectKey=medicab-${env.SERVICE_NAME} \
                          -Dsonar.host.url=http://host.docker.internal:9005 \
                          -Dsonar.token=${env.SONAR_TOKEN}
                    """
                }
            }
        }

        stage('Docker Build & Push') {
            steps {
                dir("${env.SERVICE_NAME}") {
                    sh "docker build -t ${env.DOCKER_REGISTRY}/${env.SERVICE_NAME}:${env.BUILD_NUMBER} ."
                    withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', passwordVariable: 'DOCKER_PASS', usernameVariable: 'DOCKER_USER')]) {
                        sh "echo \${DOCKER_PASS} | docker login -u \${DOCKER_USER} --password-stdin"
                        sh "docker push ${env.DOCKER_REGISTRY}/${env.SERVICE_NAME}:${env.BUILD_NUMBER}"
                    }
                }
            }
        }

        stage('GitOps Update Manifest') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'github-creds', passwordVariable: 'GIT_PASS', usernameVariable: 'GIT_USER')]) {
                    sh """
                        git config user.name "Jenkins CI"
                        git config user.email "jenkins@medicab.local"
                        sed -i 's|image: ${env.DOCKER_REGISTRY}/${env.SERVICE_NAME}:.*|image: ${env.DOCKER_REGISTRY}/${env.SERVICE_NAME}:${env.BUILD_NUMBER}|g' k8s/${env.SERVICE_NAME}/deployment.yml
                        git add k8s/${env.SERVICE_NAME}/deployment.yml
                        git commit -m "chore(gitops): update ${env.SERVICE_NAME} image to build ${env.BUILD_NUMBER} [skip ci]" || echo "Aucune modification a commiter"
                        git push https://\${GIT_USER}:\${GIT_PASS}@github.com/abdelkabirJabrane/Gestion_Cabinent_Medical_PFE.git HEAD:master
                    """
                }
            }
        }
    }
}